variable "region" {}
variable "project_name" {}
variable "vpc_cidr" {}
variable "public_subnet_dev_az1_cidr" {}
variable "public_subnet_dev_az2_cidr" {}
variable "private_app_subnet_dev_az1_id" {}
variable "private_app_subnet_dev_az2_id" {}
variable "private_data_subnet_dev_az1_id" {}
variable "private_data_subnet_dev_az2_id" {}